version: "3.8"
services:
  app:
    container_name: Backup-BE
    image: be_0810
    restart: always
    build:
      context: .
      target: backend
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    
