version: "3.8"
services:
  app:
    container_name: Backup-BE
    image: be_0810
    restart: always
    build:
      context: .
      target: backend
    volumes:
      - ./:/app
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_backup
    ports:
      - 3307:3306
    restart: always
    volumes:
      - ../dataMysql:/var/lib/mysql
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8088:80
volumes:
  ../dataMysql: